/**
 * @fileoverview gRPC-Web generated client stub for portfolio
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: portfolio.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.portfolio = require('./portfolio_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.portfolio.PortfolioServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.portfolio.PortfolioServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.portfolio.AddStockRequest,
 *   !proto.portfolio.AddStockResponse>}
 */
const methodDescriptor_PortfolioService_AddStock = new grpc.web.MethodDescriptor(
  '/portfolio.PortfolioService/AddStock',
  grpc.web.MethodType.UNARY,
  proto.portfolio.AddStockRequest,
  proto.portfolio.AddStockResponse,
  /**
   * @param {!proto.portfolio.AddStockRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.portfolio.AddStockResponse.deserializeBinary
);


/**
 * @param {!proto.portfolio.AddStockRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.portfolio.AddStockResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.portfolio.AddStockResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.portfolio.PortfolioServiceClient.prototype.addStock =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/portfolio.PortfolioService/AddStock',
      request,
      metadata || {},
      methodDescriptor_PortfolioService_AddStock,
      callback);
};


/**
 * @param {!proto.portfolio.AddStockRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.portfolio.AddStockResponse>}
 *     Promise that resolves to the response
 */
proto.portfolio.PortfolioServicePromiseClient.prototype.addStock =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/portfolio.PortfolioService/AddStock',
      request,
      metadata || {},
      methodDescriptor_PortfolioService_AddStock);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.portfolio.GetPortfolioRequest,
 *   !proto.portfolio.GetPortfolioResponse>}
 */
const methodDescriptor_PortfolioService_GetPortfolio = new grpc.web.MethodDescriptor(
  '/portfolio.PortfolioService/GetPortfolio',
  grpc.web.MethodType.UNARY,
  proto.portfolio.GetPortfolioRequest,
  proto.portfolio.GetPortfolioResponse,
  /**
   * @param {!proto.portfolio.GetPortfolioRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.portfolio.GetPortfolioResponse.deserializeBinary
);


/**
 * @param {!proto.portfolio.GetPortfolioRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.portfolio.GetPortfolioResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.portfolio.GetPortfolioResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.portfolio.PortfolioServiceClient.prototype.getPortfolio =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/portfolio.PortfolioService/GetPortfolio',
      request,
      metadata || {},
      methodDescriptor_PortfolioService_GetPortfolio,
      callback);
};


/**
 * @param {!proto.portfolio.GetPortfolioRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.portfolio.GetPortfolioResponse>}
 *     Promise that resolves to the response
 */
proto.portfolio.PortfolioServicePromiseClient.prototype.getPortfolio =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/portfolio.PortfolioService/GetPortfolio',
      request,
      metadata || {},
      methodDescriptor_PortfolioService_GetPortfolio);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.portfolio.SetPriceAlertRequest,
 *   !proto.portfolio.SetPriceAlertResponse>}
 */
const methodDescriptor_PortfolioService_SetPriceAlert = new grpc.web.MethodDescriptor(
  '/portfolio.PortfolioService/SetPriceAlert',
  grpc.web.MethodType.UNARY,
  proto.portfolio.SetPriceAlertRequest,
  proto.portfolio.SetPriceAlertResponse,
  /**
   * @param {!proto.portfolio.SetPriceAlertRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.portfolio.SetPriceAlertResponse.deserializeBinary
);


/**
 * @param {!proto.portfolio.SetPriceAlertRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.portfolio.SetPriceAlertResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.portfolio.SetPriceAlertResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.portfolio.PortfolioServiceClient.prototype.setPriceAlert =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/portfolio.PortfolioService/SetPriceAlert',
      request,
      metadata || {},
      methodDescriptor_PortfolioService_SetPriceAlert,
      callback);
};


/**
 * @param {!proto.portfolio.SetPriceAlertRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.portfolio.SetPriceAlertResponse>}
 *     Promise that resolves to the response
 */
proto.portfolio.PortfolioServicePromiseClient.prototype.setPriceAlert =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/portfolio.PortfolioService/SetPriceAlert',
      request,
      metadata || {},
      methodDescriptor_PortfolioService_SetPriceAlert);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.portfolio.StreamPricesRequest,
 *   !proto.portfolio.PriceUpdate>}
 */
const methodDescriptor_PortfolioService_StreamPrices = new grpc.web.MethodDescriptor(
  '/portfolio.PortfolioService/StreamPrices',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.portfolio.StreamPricesRequest,
  proto.portfolio.PriceUpdate,
  /**
   * @param {!proto.portfolio.StreamPricesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.portfolio.PriceUpdate.deserializeBinary
);


/**
 * @param {!proto.portfolio.StreamPricesRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.portfolio.PriceUpdate>}
 *     The XHR Node Readable Stream
 */
proto.portfolio.PortfolioServiceClient.prototype.streamPrices =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/portfolio.PortfolioService/StreamPrices',
      request,
      metadata || {},
      methodDescriptor_PortfolioService_StreamPrices);
};


/**
 * @param {!proto.portfolio.StreamPricesRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.portfolio.PriceUpdate>}
 *     The XHR Node Readable Stream
 */
proto.portfolio.PortfolioServicePromiseClient.prototype.streamPrices =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/portfolio.PortfolioService/StreamPrices',
      request,
      metadata || {},
      methodDescriptor_PortfolioService_StreamPrices);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.portfolio.RemoveStockRequest,
 *   !proto.portfolio.RemoveStockResponse>}
 */
const methodDescriptor_PortfolioService_RemoveStock = new grpc.web.MethodDescriptor(
  '/portfolio.PortfolioService/RemoveStock',
  grpc.web.MethodType.UNARY,
  proto.portfolio.RemoveStockRequest,
  proto.portfolio.RemoveStockResponse,
  /**
   * @param {!proto.portfolio.RemoveStockRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.portfolio.RemoveStockResponse.deserializeBinary
);


/**
 * @param {!proto.portfolio.RemoveStockRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.portfolio.RemoveStockResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.portfolio.RemoveStockResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.portfolio.PortfolioServiceClient.prototype.removeStock =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/portfolio.PortfolioService/RemoveStock',
      request,
      metadata || {},
      methodDescriptor_PortfolioService_RemoveStock,
      callback);
};


/**
 * @param {!proto.portfolio.RemoveStockRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.portfolio.RemoveStockResponse>}
 *     Promise that resolves to the response
 */
proto.portfolio.PortfolioServicePromiseClient.prototype.removeStock =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/portfolio.PortfolioService/RemoveStock',
      request,
      metadata || {},
      methodDescriptor_PortfolioService_RemoveStock);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.portfolio.HistoricalDataRequest,
 *   !proto.portfolio.HistoricalDataResponse>}
 */
const methodDescriptor_PortfolioService_GetHistoricalData = new grpc.web.MethodDescriptor(
  '/portfolio.PortfolioService/GetHistoricalData',
  grpc.web.MethodType.UNARY,
  proto.portfolio.HistoricalDataRequest,
  proto.portfolio.HistoricalDataResponse,
  /**
   * @param {!proto.portfolio.HistoricalDataRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.portfolio.HistoricalDataResponse.deserializeBinary
);


/**
 * @param {!proto.portfolio.HistoricalDataRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.portfolio.HistoricalDataResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.portfolio.HistoricalDataResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.portfolio.PortfolioServiceClient.prototype.getHistoricalData =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/portfolio.PortfolioService/GetHistoricalData',
      request,
      metadata || {},
      methodDescriptor_PortfolioService_GetHistoricalData,
      callback);
};


/**
 * @param {!proto.portfolio.HistoricalDataRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.portfolio.HistoricalDataResponse>}
 *     Promise that resolves to the response
 */
proto.portfolio.PortfolioServicePromiseClient.prototype.getHistoricalData =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/portfolio.PortfolioService/GetHistoricalData',
      request,
      metadata || {},
      methodDescriptor_PortfolioService_GetHistoricalData);
};


module.exports = proto.portfolio;

