/**
 * @fileoverview gRPC-Web generated client stub for portfolio
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.21.6
// source: portfolio.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as portfolio_pb from './portfolio_pb';


export class PortfolioServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorAddStock = new grpcWeb.MethodDescriptor(
    '/portfolio.PortfolioService/AddStock',
    grpcWeb.MethodType.UNARY,
    portfolio_pb.AddStockRequest,
    portfolio_pb.AddStockResponse,
    (request: portfolio_pb.AddStockRequest) => {
      return request.serializeBinary();
    },
    portfolio_pb.AddStockResponse.deserializeBinary
  );

  addStock(
    request: portfolio_pb.AddStockRequest,
    metadata: grpcWeb.Metadata | null): Promise<portfolio_pb.AddStockResponse>;

  addStock(
    request: portfolio_pb.AddStockRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: portfolio_pb.AddStockResponse) => void): grpcWeb.ClientReadableStream<portfolio_pb.AddStockResponse>;

  addStock(
    request: portfolio_pb.AddStockRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: portfolio_pb.AddStockResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/portfolio.PortfolioService/AddStock',
        request,
        metadata || {},
        this.methodDescriptorAddStock,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/portfolio.PortfolioService/AddStock',
    request,
    metadata || {},
    this.methodDescriptorAddStock);
  }

  methodDescriptorGetPortfolio = new grpcWeb.MethodDescriptor(
    '/portfolio.PortfolioService/GetPortfolio',
    grpcWeb.MethodType.UNARY,
    portfolio_pb.GetPortfolioRequest,
    portfolio_pb.GetPortfolioResponse,
    (request: portfolio_pb.GetPortfolioRequest) => {
      return request.serializeBinary();
    },
    portfolio_pb.GetPortfolioResponse.deserializeBinary
  );

  getPortfolio(
    request: portfolio_pb.GetPortfolioRequest,
    metadata: grpcWeb.Metadata | null): Promise<portfolio_pb.GetPortfolioResponse>;

  getPortfolio(
    request: portfolio_pb.GetPortfolioRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: portfolio_pb.GetPortfolioResponse) => void): grpcWeb.ClientReadableStream<portfolio_pb.GetPortfolioResponse>;

  getPortfolio(
    request: portfolio_pb.GetPortfolioRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: portfolio_pb.GetPortfolioResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/portfolio.PortfolioService/GetPortfolio',
        request,
        metadata || {},
        this.methodDescriptorGetPortfolio,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/portfolio.PortfolioService/GetPortfolio',
    request,
    metadata || {},
    this.methodDescriptorGetPortfolio);
  }

  methodDescriptorSetPriceAlert = new grpcWeb.MethodDescriptor(
    '/portfolio.PortfolioService/SetPriceAlert',
    grpcWeb.MethodType.UNARY,
    portfolio_pb.SetPriceAlertRequest,
    portfolio_pb.SetPriceAlertResponse,
    (request: portfolio_pb.SetPriceAlertRequest) => {
      return request.serializeBinary();
    },
    portfolio_pb.SetPriceAlertResponse.deserializeBinary
  );

  setPriceAlert(
    request: portfolio_pb.SetPriceAlertRequest,
    metadata: grpcWeb.Metadata | null): Promise<portfolio_pb.SetPriceAlertResponse>;

  setPriceAlert(
    request: portfolio_pb.SetPriceAlertRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: portfolio_pb.SetPriceAlertResponse) => void): grpcWeb.ClientReadableStream<portfolio_pb.SetPriceAlertResponse>;

  setPriceAlert(
    request: portfolio_pb.SetPriceAlertRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: portfolio_pb.SetPriceAlertResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/portfolio.PortfolioService/SetPriceAlert',
        request,
        metadata || {},
        this.methodDescriptorSetPriceAlert,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/portfolio.PortfolioService/SetPriceAlert',
    request,
    metadata || {},
    this.methodDescriptorSetPriceAlert);
  }

  methodDescriptorStreamPrices = new grpcWeb.MethodDescriptor(
    '/portfolio.PortfolioService/StreamPrices',
    grpcWeb.MethodType.SERVER_STREAMING,
    portfolio_pb.StreamPricesRequest,
    portfolio_pb.PriceUpdate,
    (request: portfolio_pb.StreamPricesRequest) => {
      return request.serializeBinary();
    },
    portfolio_pb.PriceUpdate.deserializeBinary
  );

  streamPrices(
    request: portfolio_pb.StreamPricesRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<portfolio_pb.PriceUpdate> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/portfolio.PortfolioService/StreamPrices',
      request,
      metadata || {},
      this.methodDescriptorStreamPrices);
  }

  methodDescriptorRemoveStock = new grpcWeb.MethodDescriptor(
    '/portfolio.PortfolioService/RemoveStock',
    grpcWeb.MethodType.UNARY,
    portfolio_pb.RemoveStockRequest,
    portfolio_pb.RemoveStockResponse,
    (request: portfolio_pb.RemoveStockRequest) => {
      return request.serializeBinary();
    },
    portfolio_pb.RemoveStockResponse.deserializeBinary
  );

  removeStock(
    request: portfolio_pb.RemoveStockRequest,
    metadata: grpcWeb.Metadata | null): Promise<portfolio_pb.RemoveStockResponse>;

  removeStock(
    request: portfolio_pb.RemoveStockRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: portfolio_pb.RemoveStockResponse) => void): grpcWeb.ClientReadableStream<portfolio_pb.RemoveStockResponse>;

  removeStock(
    request: portfolio_pb.RemoveStockRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: portfolio_pb.RemoveStockResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/portfolio.PortfolioService/RemoveStock',
        request,
        metadata || {},
        this.methodDescriptorRemoveStock,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/portfolio.PortfolioService/RemoveStock',
    request,
    metadata || {},
    this.methodDescriptorRemoveStock);
  }

  methodDescriptorGetHistoricalData = new grpcWeb.MethodDescriptor(
    '/portfolio.PortfolioService/GetHistoricalData',
    grpcWeb.MethodType.UNARY,
    portfolio_pb.HistoricalDataRequest,
    portfolio_pb.HistoricalDataResponse,
    (request: portfolio_pb.HistoricalDataRequest) => {
      return request.serializeBinary();
    },
    portfolio_pb.HistoricalDataResponse.deserializeBinary
  );

  getHistoricalData(
    request: portfolio_pb.HistoricalDataRequest,
    metadata: grpcWeb.Metadata | null): Promise<portfolio_pb.HistoricalDataResponse>;

  getHistoricalData(
    request: portfolio_pb.HistoricalDataRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: portfolio_pb.HistoricalDataResponse) => void): grpcWeb.ClientReadableStream<portfolio_pb.HistoricalDataResponse>;

  getHistoricalData(
    request: portfolio_pb.HistoricalDataRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: portfolio_pb.HistoricalDataResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/portfolio.PortfolioService/GetHistoricalData',
        request,
        metadata || {},
        this.methodDescriptorGetHistoricalData,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/portfolio.PortfolioService/GetHistoricalData',
    request,
    metadata || {},
    this.methodDescriptorGetHistoricalData);
  }

}

