"use strict";
/**
 * @fileoverview gRPC-Web generated client stub for portfolio
 * @enhanceable
 * @public
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PortfolioServiceClient = void 0;
// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.21.6
// source: portfolio.proto
/* eslint-disable */
// @ts-nocheck
const grpcWeb = require("grpc-web");
const portfolio_pb = require("./portfolio_pb");
class PortfolioServiceClient {
    constructor(hostname, credentials, options) {
        this.methodDescriptorAddStock = new grpcWeb.MethodDescriptor('/portfolio.PortfolioService/AddStock', grpcWeb.MethodType.UNARY, portfolio_pb.AddStockRequest, portfolio_pb.AddStockResponse, (request) => {
            return request.serializeBinary();
        }, portfolio_pb.AddStockResponse.deserializeBinary);
        this.methodDescriptorGetPortfolio = new grpcWeb.MethodDescriptor('/portfolio.PortfolioService/GetPortfolio', grpcWeb.MethodType.UNARY, portfolio_pb.GetPortfolioRequest, portfolio_pb.GetPortfolioResponse, (request) => {
            return request.serializeBinary();
        }, portfolio_pb.GetPortfolioResponse.deserializeBinary);
        this.methodDescriptorSetPriceAlert = new grpcWeb.MethodDescriptor('/portfolio.PortfolioService/SetPriceAlert', grpcWeb.MethodType.UNARY, portfolio_pb.SetPriceAlertRequest, portfolio_pb.SetPriceAlertResponse, (request) => {
            return request.serializeBinary();
        }, portfolio_pb.SetPriceAlertResponse.deserializeBinary);
        this.methodDescriptorStreamPrices = new grpcWeb.MethodDescriptor('/portfolio.PortfolioService/StreamPrices', grpcWeb.MethodType.SERVER_STREAMING, portfolio_pb.StreamPricesRequest, portfolio_pb.PriceUpdate, (request) => {
            return request.serializeBinary();
        }, portfolio_pb.PriceUpdate.deserializeBinary);
        this.methodDescriptorRemoveStock = new grpcWeb.MethodDescriptor('/portfolio.PortfolioService/RemoveStock', grpcWeb.MethodType.UNARY, portfolio_pb.RemoveStockRequest, portfolio_pb.RemoveStockResponse, (request) => {
            return request.serializeBinary();
        }, portfolio_pb.RemoveStockResponse.deserializeBinary);
        this.methodDescriptorGetHistoricalData = new grpcWeb.MethodDescriptor('/portfolio.PortfolioService/GetHistoricalData', grpcWeb.MethodType.UNARY, portfolio_pb.HistoricalDataRequest, portfolio_pb.HistoricalDataResponse, (request) => {
            return request.serializeBinary();
        }, portfolio_pb.HistoricalDataResponse.deserializeBinary);
        if (!options)
            options = {};
        if (!credentials)
            credentials = {};
        options['format'] = 'text';
        this.client_ = new grpcWeb.GrpcWebClientBase(options);
        this.hostname_ = hostname.replace(/\/+$/, '');
        this.credentials_ = credentials;
        this.options_ = options;
    }
    addStock(request, metadata, callback) {
        if (callback !== undefined) {
            return this.client_.rpcCall(this.hostname_ +
                '/portfolio.PortfolioService/AddStock', request, metadata || {}, this.methodDescriptorAddStock, callback);
        }
        return this.client_.unaryCall(this.hostname_ +
            '/portfolio.PortfolioService/AddStock', request, metadata || {}, this.methodDescriptorAddStock);
    }
    getPortfolio(request, metadata, callback) {
        if (callback !== undefined) {
            return this.client_.rpcCall(this.hostname_ +
                '/portfolio.PortfolioService/GetPortfolio', request, metadata || {}, this.methodDescriptorGetPortfolio, callback);
        }
        return this.client_.unaryCall(this.hostname_ +
            '/portfolio.PortfolioService/GetPortfolio', request, metadata || {}, this.methodDescriptorGetPortfolio);
    }
    setPriceAlert(request, metadata, callback) {
        if (callback !== undefined) {
            return this.client_.rpcCall(this.hostname_ +
                '/portfolio.PortfolioService/SetPriceAlert', request, metadata || {}, this.methodDescriptorSetPriceAlert, callback);
        }
        return this.client_.unaryCall(this.hostname_ +
            '/portfolio.PortfolioService/SetPriceAlert', request, metadata || {}, this.methodDescriptorSetPriceAlert);
    }
    streamPrices(request, metadata) {
        return this.client_.serverStreaming(this.hostname_ +
            '/portfolio.PortfolioService/StreamPrices', request, metadata || {}, this.methodDescriptorStreamPrices);
    }
    removeStock(request, metadata, callback) {
        if (callback !== undefined) {
            return this.client_.rpcCall(this.hostname_ +
                '/portfolio.PortfolioService/RemoveStock', request, metadata || {}, this.methodDescriptorRemoveStock, callback);
        }
        return this.client_.unaryCall(this.hostname_ +
            '/portfolio.PortfolioService/RemoveStock', request, metadata || {}, this.methodDescriptorRemoveStock);
    }
    getHistoricalData(request, metadata, callback) {
        if (callback !== undefined) {
            return this.client_.rpcCall(this.hostname_ +
                '/portfolio.PortfolioService/GetHistoricalData', request, metadata || {}, this.methodDescriptorGetHistoricalData, callback);
        }
        return this.client_.unaryCall(this.hostname_ +
            '/portfolio.PortfolioService/GetHistoricalData', request, metadata || {}, this.methodDescriptorGetHistoricalData);
    }
}
exports.PortfolioServiceClient = PortfolioServiceClient;
